### ISSUE TITLE
Добавить файл CONTRIBUTING.md

### ISSUE THREAD

**Issue by vozemer** [pupenasan/Git4All#5]
Добавление этого файла позволит описать правила взаимодействия членов сообщества и описать процесс внедрения изменений в главную ветвь

**Comment by pupenasan** [comment]
> 
> 
> Добавление этого файла позволит описать правила взаимодействия членов сообщества и описать процесс внедрения изменений в главную ветвь

Это хорошо, толькл что там писать?

**Comment by pupenasan** [comment]
Перший варіант [написав](https://github.com/pupenasan/Git4All/blob/master/CONTRIBUTING.md)
